
function calling() {
    try {
    } catch (error) {
        console.log('Error');
    } finally {
        console.log('');
        console.log('');
        console.log('');
        console.log('');
    }
}