function handleError(err) {
    throw err;
}


function main(){
    const e = new Error('Error: ', err);
    handleError(e);
}